services:
  web-app:
    image: ghcr.io/sitecite/sitecite:v1.0
    container_name: sitecite
    ports:
      - "9404:9404" # Port that sitecite runs on, default is 9404
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always
    depends_on:
      - db
    volumes:
      - setup_data:/usr/src/app/data
      - ./config.yaml:/usr/src/app/config.yaml
      - ./.env:/usr/src/app/.env
      - ./whitelist.js:/usr/src/app/whitelist.js

  db:
    image: mysql:8.0
    container_name: sitecite_db
    restart: always
    # WHEN UPDATING MYSQL CREDENTIALS MAKE SURE TO ALSO UPDATE THEM IN THE .ENV FILE!!!
    environment:
      MYSQL_ROOT_PASSWORD: "fkP7pZ2hD1cA5wpdzx6HI75Fli7yu9f0XQ85SLT1" # Default password, recommended to change for security
      MYSQL_DATABASE: "citesite" # No need to change, but you can if you like!
      MYSQL_USER: "citesite" # No need to change, but you can if you like!
      MYSQL_PASSWORD: "fkP7pZ2hD1cA5wpdzx6HI75Fli7yu9f0XQ85SLT1" # Default password, recommended to change for security
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  setup_data:
